name: CI

on:
  pull_request:
    branches: [ master ]
    
env:
  Framework: net6.0-windows
  Configuration: Release
  Solution_Name: WinRemoteControl.sln
  Csproj_Project_Path: WinRemoteControl\WinRemoteControl.csproj
  Csproj_Subfolder: WinRemoteControl

jobs:

  build:  
    runs-on: windows-2022
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x

    # Execute all unit tests in the solution
    #- name: Execute unit tests
    #  run: dotnet test
    
    # Generate build artifacts
    - name: Build application - 32-bit
      run: dotnet build ${{ env.Csproj_Project_Path }} /p:Configuration=${{ env.Configuration }}   